extends Node

onready var INTERIM_OCCURED = false

var ICOSAHEDRON_CONVICTED
var SPHERE_CONVICTED
var TORUS_CONVICTED
var PYRAMID_CONVICTED

var CURRENT_SCENE
var TRIAL_NAME
var CLOCK_TIME

func all_convicted():
	return ICOSAHEDRON_CONVICTED and SPHERE_CONVICTED and TORUS_CONVICTED and PYRAMID_CONVICTED
