extends Node


var ICOSAHEDRON_CONVICTED
var SPHERE_CONVICTED
var TORUS_CONVICTED
var PYRAMID_CONVICTED

func all_convicted():
	return ICOSAHEDRON_CONVICTED and SPHERE_CONVICTED and TORUS_CONVICTED and PYRAMID_CONVICTED
